# Generated by Django 4.0.1 on 2022-01-07 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('avatar', models.ImageField(upload_to='static/')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
