# Generated by Django 4.0.1 on 2022-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
